# Generated by Django 3.2.7 on 2021-09-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0002_city_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour_attention', models.DateTimeField()),
                ('date_hour_attention_finish', models.DateTimeField()),
                ('company', models.CharField(max_length=150)),
                ('affair', models.CharField(max_length=300)),
                ('response', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_register.city')),
            ],
        ),
        migrations.DeleteModel(
            name='request',
        ),
    ]
