# Generated by Django 3.2.7 on 2021-09-15 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_register', '0002_auto_20210914_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 15, 1, 3, 24, 656067, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
